### ISSUE TITLE
/var/poolparty has AWS access and secret key

### ISSUE THREAD

**Issue by pingali** [auser/poolparty#3]
This is a security hole. 

/var/poolparty/dr_configure/clouds.json 

has both the access_key and secret_access_key. Do they have to be there? Could we
create a /etc/poolparty/<>.conf  file in which this information resides, possibly encrypted?

**Comment by fairchild** [comment]
perhaps an after_configure hook to clean out sensitive files. 
At some point the keys need to be available so that a node can expand the cloud. 
How would you  encrypt the keys?  It would be great if there was some way to protect these keys better. 
Much of /var/poolparty is just cached info used for bootstrap and configure.  Possibly we should rm the cache, or replace the data with symlinks?  For, know I'd be happy to just move the keys to /etc/poolparty and leave the cache.

**Comment by pingali** [comment]
There are few different alternatives: 
1. Cleanup after use. This would require us to upload the json again each time we need it on the instance.
2. Avoid including them when the cloud auto-expand/contract is not required. Same downside as above.
3. We could pass them through the user-data so that it is not on the disk should the machine be compromised. The problem however is that if the secret key changes during the lifetime of an instance, we cannot update the user-data
4. We could pipe the .json file through an ERB processor to decrypt when needed as shown below 
http://skwpspace.com/2006/08/29/encrypted-db-passwords-for-rails-with-databaseyml-and-erb/
5. We could pass the keys in a file whose name can be derived somehow from some data passed in the json. The keys in this case are on the instance.

**Comment by tralfamadude** [comment]
Is this bug still present?  I cannot find /var/poolparty/dr_configure/clouds.json but the secret_access_key could be cached elsewhere.

If this bug is not fixed, documentation should clearly state this deficiency and the workaround.  My policy is to never put such credentials on a stored ami image and because I created an image without knowing about this bug, it appears that my chosen policy has been violated.

**Comment by jashmenn** [comment]
testing sd
